include:
  - board: nice_nano_v2
    shield: slicemk_ergodox_leftsingle
  - board: nice_nano_v2
    shield: slicemk_ergodox_rightsingle
  - board: nordic_nrf52840_dongle_slicemk 
    shield: slicemk_ergodox_dongle
